---
- name: keyfile | stat
  stat:
    path: "{{ dst_keyfile }}"
  register: keyfile_check

- name: keyfile | set fact
  set_fact:
    keyfile_fact: "{{ keyfile_check.stat.exists }}"

- name: keyfile | block to check which host(s) have the file
  block:

    - name: keyfile | create dict of keyfile check
      set_fact:
        keyfile_status: "{{ dict(keys|zip(values)) }}"
      vars:
        keys: "{{ ansible_play_hosts }}"
        values: "{{ ansible_play_hosts |
                    map('extract', hostvars, ['keyfile_fact'])
                    | list }}"

    - name: keyfile | set fact when no host has the file
      set_fact:
        keyfile_none: true
      when: keyfile_status.values() | list is not any

    - name: keyfile | set fact when a host does not has the file
      set_fact:
        keyfile_all: false
      when: keyfile_status.values() | list is any

    - name: keyfile | set fact when all hosts have the files
      set_fact:
        keyfile_all: true
      when: keyfile_status.values() | list is all

  run_once: true

- name: Ensure autogenerated certificate directory exists
  file:
    dest: "{{ dst_keyfile | dirname }}"
    state: directory

- name: keyfile | block to copy keyfile when none has one
  block:
    - name: keyfile | set fact to copy keyfile from a host
      set_fact:
        keyfile_host: "{{ item }}"
      run_once: true
      loop: "{{ ansible_play_hosts }}"

    - name: keyfile | find out CA file exists or not
      stat:
        path: "{{ dst_cafile }}"
      register: dst_cafile_present

    - name: keyfile | create CA when none has a keyfile
      shell: >-
        {{ es_home }}/bin/elasticsearch-certutil ca --days 10950 -out {{ dst_cafile }} --pass {{ dst_cafile_password }}
      register: new_keyfile
      when: inventory_hostname == keyfile_host
        and dst_cafile_present.stat.exists == false

    - name: keyfile | create when none has a keyfile
      shell: >-
        {{ es_home }}/bin/elasticsearch-certutil cert --ca {{ dst_cafile }} --ca-pass {{ dst_cafile_password }} --days 10950 -out {{ dst_keyfile }} --pass {{ dst_keyfile_password }}
      register: new_keyfile
      when: inventory_hostname == keyfile_host

    - name: keyfile | fetch keyfile
      fetch:
        src: "{{ dst_keyfile }}"
        flat: true
        dest: "{{ tmp_keyfile }}"
      delegate_to: "{{ keyfile_host }}"

    - name: keyfile | copy required files to remaining hosts
      copy:
        src: "{{ tmp_keyfile }}"
        dest: "{{ dst_keyfile }}"

  when: keyfile_none is defined

- name: keyfile | block to copy keyfile when at least one is missing
  block:
    - name: keyfile | set fact to copy keyfile from a host
      set_fact:
        keyfile_host: "{{ ansible_hostname }}"
      when: keyfile_fact is defined and keyfile_fact
      
    - name: keyfile | fetch keyfile
      fetch:
        src: "{{ dst_keyfile }}"
        flat: true
        dest: "{{ tmp_keyfile }}"
      delegate_to: "{{ keyfile_host }}"
      when: keyfile_host is defined

    - name: keyfile | copy required files to remaining hosts
      copy:
        src: "{{ tmp_keyfile }}"
        dest: "{{ dst_keyfile }}"

  when: keyfile_all is defined and not keyfile_all

- name: keyfile | ensure absence from localhost
  file:
    path: "{{ tmp_keyfile }}"
    state: absent
  run_once: true
  delegate_to: localhost
  become: false
